config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'projects#index'

  resources :projects do
    resources :tasks, shallow: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, -> { order(position: :asc) }, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 2 }
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  acts_as_list scope: :project
  validates :text, presence: true,
                    length: { minimum: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :danger
  before_action :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, except: %i[index new create]

  def index
    @projects = current_user.projects
  end

  def new
    @project = Project.new
  end

  def edit; end

  def create
    @project = Project.new(project_params.merge(user_id: current_user.id))
    unless @project.save
      flash.now.alert = @project.errors.full_messages.to_sentence
      render 'shared/errors'
    end
  end

  def update
    unless @project.update(project_params)
      flash.now.alert = @project.errors.full_messages.to_sentence
      render 'shared/errors'
    end
  end

  def destroy
    @project.destroy
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title)
  end
end

# TODO validation, complete, deadline, sort_up - sort down,

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, except: %i[new create]

  def new
    @project = Project.find(params[:project_id])
    @task = @project.tasks.new
  end

  def edit; end

  def create
    @task = Task.new(tasks_params.merge({ project_id: params[:project_id] }))
    unless @task.save
      flash.now.alert = @task.errors.full_messages.to_sentence
      render 'shared/errors'
    end
  end

  def update
    if params[:move_higher] == "true"
      @task.move_higher
    elsif params[:move_lower] == "true"
      @task.move_lower
    else
      unless @task.update(tasks_params)
        flash.now.alert = @task.errors.full_messages.to_sentence
        render 'shared/errors'
      end
    end
  end

  def destroy
    @task.destroy
  end

  private

  def find_task
    @task = Task.find(params[:id])
  end

  def tasks_params
    params.require(:task).permit(:text, :complete, :deadline)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  </head>
  <body>
    <div class='container'>
      <%= yield %>
    <div>
  </body>
</html>

app/views/projects/_form.html.erb
<div class='project-form'>
  <%= form_for @project, remote: true do |form| %>
    <%= form.label :title, class:'black-text' %>
    <%= form.text_field :title %>
    <%= form.submit 'Accept', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/projects/_project.html.erb
<div id="project-<%= project.id %>">
  <div class='project-row' id="project-row-<%= project.id %>">
    <i class='glyphicon glyphicon-calendar project-calendar'></i>
    <div class='project-name' id="project-name-<%= project.id %>">
      <%= project.title %>
    </div>
    <div id="project-links-<%= project.id %>">
      <%= link_to ' ', edit_project_path(project), remote: true, class: 'glyphicon glyphicon-pencil project-edit' %>
      <span class='project-links-separate'>|</span>
      <%= link_to ' ', project, remote: true, method: :delete, class: 'glyphicon glyphicon-trash project-delete' %>
    </div>
  </div>
  <div class='task-form'>
    <i class='glyphicon glyphicon-plus plus-green' aria-hidden="true"></i>
    <%= form_for([project, Task.new], remote: true) do |form| %>
      <%= form.text_field :text, placeholder: 'Start typing here to create a task...', class: 'task-form-field' %>
      <%= form.submit 'Add Task', class: 'btn btn-success' %>
    <% end %>
  </div>
  <div class='task-list' id="task-list-<%= project.id %>">
    <% project.tasks.each do |task| %>
      <%= render 'tasks/task', task: task %>
    <% end %>
  </div>
</div>

app/views/projects/create.js.erb
$('.project-form').remove();
$('#project-new-button').show();
$('.project-list').append("<%= j render @project %>");

app/views/projects/destroy.js.erb
$('#project-<%= @project.id %>').fadeOut();

app/views/projects/edit.js.erb
$('#project-name-<%= @project.id %>').hide();
$('#project-row-<%= @project.id %>').append("<%= j render 'form', project: @project %>");
$('#project-links-<%= @project.id %>').hide()

app/views/projects/index.html.erb
<div class='title'>
  <h1>SIMPLE TODO LISTS</h1>
  <h4>FROM RUBY GARAGE</h4>
</div>
<div id='flash'>
  <%= render "shared/flash" %>
</div>
<div class='project-list'>
   <%= render @projects %>
</div>
<div class='center' id='project-new-link'>
  <div id='project-new-button'>
    <%= link_to new_project_path, remote: true do %>
      <button class='btn btn-primary btn-lg'>
        <i class='glyphicon glyphicon-plus black-text plus-black' aria-hidden="true"></i>
        <span>&nbsp;Add TODO List</span>
      </button>
    <% end %>
  </div>
</div>
<p class='center'>
  © Ruby Garage
</p>

app/views/projects/new.js.erb
$('#project-new-button').hide();
$('#project-new-link').append("<%= j render 'form', project: @project %>")

app/views/projects/update.js.erb
$('#project-<%= @project.id %>').replaceWith("<%= j render @project %>");

app/views/shared/_flash.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

app/views/shared/errors.js.erb
$('#flash').show();
$('#flash').html("<%= j render partial: "shared/flash" %>");
$('#flash').fadeOut(3000);

app/views/tasks/_form.html.erb
<div class='task-form-edit'>
  <%= form_for(task, remote: true) do |form| %>
    <%= form.label :text %>
    <%= form.text_field :text %>
    <%= form.date_field :deadline %>
    <%= form.submit 'Edit', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/tasks/_task.html.erb
<div class='task-row' id="task-row-<%= task.id %>">
    <% if task.complete == true %>
      <div class='task-complete' id="task-complete-<%= task.id %>">
        <%= link_to task_path(task, task: { complete: false }), remote: true, method: :put do %>
          <i class='glyphicon glyphicon-check' aria-hidden="true"></i>
        <% end %>
      </div>
      <div class='empty-div'></div>
      <div class='task-content task-complete-text' id="task-content-<%= task.id %>">
        <%= task.text %>
      </div>
    <% else %>
      <div class='task-complete' id="task-complete-<%= task.id %>">
        <%= link_to task_path(task, task: { complete: true }), remote: true, method: :put do %>
          <i class='glyphicon glyphicon-unchecked' aria-hidden="true"></i>
        <% end %>
      </div>
      <div class='empty-div'></div>
      <div class='task-content' id="task-content-<%= task.id %>">
        <%= task.text %>
      </div>
    <% end %>
  <div class='deadline'>
    <span>
      <%= task.deadline.strftime('%m/%d/%y') if task.deadline.present? %>
    </span>
  </div>
  <div class='tasks-links' id="task-links-<%= task.id %>">
    <div class='arrows'>
      <%= link_to ' ', task_path(task, move_higher: true), remote: true, method: :put, class: 'glyphicon glyphicon-arrow-up task-link' %>
      &nbsp;
      <%= link_to ' ', task_path(task, move_lower: true), remote: true, method: :put, class: 'glyphicon glyphicon-arrow-down task-link' %>
    </div>
    <span class='tasks-links-separator'>|</span>
    <%= link_to ' ', task, remote: true, method: :delete, class: 'glyphicon glyphicon-trash task-link' %>
    <span class='tasks-links-separator'>|</span>
    <%= link_to ' ', edit_task_path(task), remote: true, class: 'glyphicon glyphicon-pencil task-link' %>
  </div>
</div>

app/views/tasks/create.js.erb
$('#task-list-<%= @task.project_id %>').append("<%= j render @task %>")
$('.task-form-field').val('')

app/views/tasks/destroy.js.erb
$('#task-row-<%= @task.id %>').fadeOut();

app/views/tasks/edit.js.erb
$('#task-complete-icon-<%= @task.id %>').hide();
$('#task-links-<%= @task.id %>').hide();
$('#task-complete-<%= @task.id %>').hide();
$('#task-content-<%= @task.id %>').replaceWith('<%= j render 'form', task: @task %>');

app/views/tasks/new.js.erb
$('#new-task').html("<%= j render 'form', task: @task, project: @project %>")

app/views/tasks/update.js.erb
$('#project-<%= @task.project_id %>').replaceWith("<%= j render @task.project %>");